export const ACTIONS = {
  IDLE: 'HIDE',
  START: 'START',
  COUNTDOWN: 'COUNTDOWN',
  OPEN: 'OPEN',
  CELEBRATE: 'CELEBRATE',
  RESET: 'RESET',
  SHAKE: 'SHAKE',
  MOVE: 'MOVE',
  UNLOCK: 'UNLOCK',
  CHECK: 'CHECK',
};
